site_name: Interactive Animation
theme: 
  name: simple-blog
  sidebar: true
  navigation_depth: 2
  components:
    title: false
    preview: true
  theme_style: light
  logo: img/interactiveanimation_logo.png
  favicon: img/interactiveanimation_logo.png
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
nav:
  - ğŸ“œ Syllabus: syllabus.md
  - ğŸ“… Schedule: schedule.md 
  - ğŸ› ï¸ Resources: resources.md
  - ğŸ“Œ Assignments:
    - How To Submit: how-to-submit.md
    - Survey: survey.md
    - Reading/Media Response: reading-media.md
    - Project 1: project-1.md
    - Project 2: project-2.md