site_name: ğŸ  DESMA127 Interactive Animation
theme: 
  name: simple-blog
  sidebar: true
  navigation_depth: 2
  components:
    title: false
    preview: true
  theme_style: light
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
nav:
  - ğŸ  Home: index.md